import type { Metadata } from "next";
import "./globals.css";
import NavbarDemo from "@/components/Navbar";
import { EB_Garamond } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const eB_Garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-merriweather",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ma Book",
  description: "Generated by Ma Book",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${eB_Garamond.variable}`}>
      <body className={``}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        > 
          <NavbarDemo />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
