import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { EB_Garamond } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-eb-garamond",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ma Book",
  description: "Generated by Ma Book",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ebGaramond.variable} font-eb-garamond`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange  
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
